name: CI-CD

on: [push]

jobs: 
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - run: python -m inittest test.py

deploy:
  runs-on: ubuntu-latest
  needs: test
  if: success()

  steps:
    - uses: actions/checkout@v3

    - name: deployment
      run: |
          sudo mkdir -p /var/www/projedct
          cd /var/www/project
          sudo git clone https://github.com/NoKiaWF/Lab_3.git
          echo "Successfully deployed"
